### PR TITLE
Suppress external sources from style checking

### PR DESCRIPTION
**Pull request by teosz**
cc @BirsuIonut

### CODE REVIEW

**Comment by BirsuIonut** [comment]
I cannot see any new functionality added by your commit. Is there any reason why we need it? Take into consideration that the API is a .jar file and it contains only .class files, which are not checked by the checkstyle script anyway.

**Comment by teosz** [comment]
`GSON` library is `com/` and it does not respects the checkstyle. This is why checkstyler fails even if my code does. 
Is not possible to store `GSON`  in `.class` files because `cleanHomework` will delete them so `com/` should be ignored by checkstyler

**Comment by teosz** [comment]
given the deadline I would like to bump up this thread @BirsulIonut

**Comment by adrianacd** [comment]
@teosz Ionut replied to you on the forum, you just need to mention in Readme that you use this library and why you needed it, and we will manually cancel the points you lost on vmchecker when we evaluate the homework.

**Comment by teosz** [comment]
thanks a lot @adrianacd 
I guess this can be closed.

**Pull request closed without merging**
